/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package student_registration;

import javax.swing.JOptionPane;

/**
 *
 * @author Pasini
 */
public class Loginpage extends javax.swing.JFrame {

    /** Creates new form Loginpage */
    public Loginpage() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        dis_username = new javax.swing.JTextField();
        login_submit = new javax.swing.JButton();
        login_clear = new javax.swing.JButton();
        dis_password = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));
        jPanel1.setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/student_registration/photo.jpg"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(100, 20, 240, 130);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("user name:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(24, 210, 120, 20);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("password :");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(20, 250, 80, 20);
        jPanel1.add(dis_username);
        dis_username.setBounds(120, 210, 250, 30);

        login_submit.setBackground(new java.awt.Color(255, 102, 102));
        login_submit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        login_submit.setText("submit");
        login_submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                login_submitActionPerformed(evt);
            }
        });
        jPanel1.add(login_submit);
        login_submit.setBounds(193, 340, 80, 30);

        login_clear.setBackground(new java.awt.Color(255, 102, 102));
        login_clear.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        login_clear.setText("clear");
        jPanel1.add(login_clear);
        login_clear.setBounds(333, 340, 80, 30);
        jPanel1.add(dis_password);
        dis_password.setBounds(120, 250, 250, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 468, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 417, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void login_submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_login_submitActionPerformed
   for(int i=0;i<Homepage.US.size();i++){
        Encapsulastion_class u = Homepage.US.get(i);
        if(dis_username.getText().equals(u.getUsername())&& dis_password.getText().equals((u.getPassword()))){
        

            
        Homepage.homelabel.setText(u.getName());
        this.dispose();}
        else{JOptionPane.showMessageDialog(this,"incorrect username or password","Messagebox",JOptionPane.ERROR_MESSAGE);
              }  } 
  
    }//GEN-LAST:event_login_submitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Loginpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Loginpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Loginpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Loginpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Loginpage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField dis_password;
    private javax.swing.JTextField dis_username;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton login_clear;
    private javax.swing.JButton login_submit;
    // End of variables declaration//GEN-END:variables

}
