/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package student_registration;

import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectOutputStream;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Pasini
 */
public class Registrtion_form extends javax.swing.JFrame {

    /**
     * Creates new form Registrtion_form
     */
    public Registrtion_form() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        male_radio = new javax.swing.JRadioButton();
        female_radio = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        Disid = new javax.swing.JTextField();
        Disname = new javax.swing.JTextField();
        Disaddress = new javax.swing.JTextField();
        Dismobile = new javax.swing.JTextField();
        Disusername = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jComboBox3 = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        signup_table = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        Dispassword = new javax.swing.JPasswordField();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setName("registration form"); // NOI18N

        jPanel1.setBackground(new java.awt.Color(255, 153, 153));
        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 255));
        jLabel2.setText("Registration form");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(210, 20, 350, 50);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setText("ID num :");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(20, 110, 110, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setText("Name :");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(20, 170, 120, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setText(" Address :");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(10, 230, 130, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel6.setText("Mobile num :");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(10, 290, 160, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel7.setText("Gender :");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(10, 350, 130, 30);

        male_radio.setBackground(new java.awt.Color(255, 153, 153));
        buttonGroup1.add(male_radio);
        male_radio.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        male_radio.setText("male");
        jPanel1.add(male_radio);
        male_radio.setBounds(150, 350, 69, 31);

        female_radio.setBackground(new java.awt.Color(255, 153, 153));
        buttonGroup1.add(female_radio);
        female_radio.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        female_radio.setText("female");
        female_radio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                female_radioActionPerformed(evt);
            }
        });
        jPanel1.add(female_radio);
        female_radio.setBounds(270, 350, 93, 30);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel8.setText("B'day:");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(20, 410, 110, 40);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel9.setText("User name:");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(20, 470, 140, 30);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel10.setText("password:");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(20, 530, 130, 40);

        Disid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DisidActionPerformed(evt);
            }
        });
        Disid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                DisidKeyPressed(evt);
            }
        });
        jPanel1.add(Disid);
        Disid.setBounds(180, 120, 200, 30);

        Disname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DisnameActionPerformed(evt);
            }
        });
        jPanel1.add(Disname);
        Disname.setBounds(180, 170, 350, 40);

        Disaddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DisaddressActionPerformed(evt);
            }
        });
        jPanel1.add(Disaddress);
        Disaddress.setBounds(180, 240, 360, 50);

        Dismobile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DismobileActionPerformed(evt);
            }
        });
        jPanel1.add(Dismobile);
        Dismobile.setBounds(180, 300, 230, 20);

        Disusername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DisusernameActionPerformed(evt);
            }
        });
        jPanel1.add(Disusername);
        Disusername.setBounds(180, 480, 270, 30);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Day", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox1);
        jComboBox1.setBounds(164, 410, 60, 30);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "month", "Jan", "Feb", "Mar", "Apr", "May", "June", "July", "August", "Sept", "Oct", "Nov", "Dec" }));
        jPanel1.add(jComboBox2);
        jComboBox2.setBounds(245, 410, 60, 30);

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "year", "1992", "1993", "1994", "1995", "1996", "1997", "1998", "1999", "2000", "2001", "2002" }));
        jPanel1.add(jComboBox3);
        jComboBox3.setBounds(327, 410, 60, 30);

        signup_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Id", "Name", "mobile", "gender"
            }
        ));
        jScrollPane1.setViewportView(signup_table);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(450, 340, 330, 120);

        jButton1.setBackground(new java.awt.Color(0, 102, 255));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("Submit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(413, 583, 100, 40);

        jButton2.setBackground(new java.awt.Color(0, 102, 255));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setText("clear");
        jPanel1.add(jButton2);
        jButton2.setBounds(603, 583, 90, 40);

        Dispassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DispasswordActionPerformed(evt);
            }
        });
        jPanel1.add(Dispassword);
        Dispassword.setBounds(180, 540, 270, 20);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 792, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 667, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void female_radioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_female_radioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_female_radioActionPerformed

    private void DisidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DisidActionPerformed

    }//GEN-LAST:event_DisidActionPerformed

    private void DismobileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DismobileActionPerformed

    }//GEN-LAST:event_DismobileActionPerformed

    private void DisnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DisnameActionPerformed

    }//GEN-LAST:event_DisnameActionPerformed

    private void DisaddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DisaddressActionPerformed

    }//GEN-LAST:event_DisaddressActionPerformed

    private void DisusernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DisusernameActionPerformed

    }//GEN-LAST:event_DisusernameActionPerformed

    private void DispasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DispasswordActionPerformed

    }//GEN-LAST:event_DispasswordActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed

    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (Dismobile.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Text field is empty", "Message box", JOptionPane.ERROR_MESSAGE);
        } else if (Disid.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Text field is empty", "Message box", JOptionPane.ERROR_MESSAGE);
        } else if (Disname.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Text field is empty", "Message box", JOptionPane.ERROR_MESSAGE);
        } else if (Disaddress.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Text field is empty", "Message box", JOptionPane.ERROR_MESSAGE);
        } else if (Disusername.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Text field is empty", "Message box", JOptionPane.ERROR_MESSAGE);
        } else if (Dispassword.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Text field is empty", "Message box", JOptionPane.ERROR_MESSAGE);
        } else if (!(male_radio.isSelected() || female_radio.isSelected())) {
            JOptionPane.showMessageDialog(this, "select your gender", "Message box", JOptionPane.ERROR_MESSAGE);
        } else if (jComboBox1.getSelectedItem().toString().equals("Day")) {
            JOptionPane.showMessageDialog(this, "Text field is empty", "Message box", JOptionPane.ERROR_MESSAGE);
        } else if (jComboBox2.getSelectedItem().toString().equals("month")) {
            JOptionPane.showMessageDialog(this, "Text field is empty", "Message box", JOptionPane.ERROR_MESSAGE);
        } else if (jComboBox3.getSelectedItem().toString().equals("year")) {
            JOptionPane.showMessageDialog(this, "Text field is empty", "Message box", JOptionPane.ERROR_MESSAGE);
        } else {
            Encapsulastion_class u = new Encapsulastion_class();
            u.setId(Disid.getText());
            u.setName(Disname.getText());
            u.setAddress(Disaddress.getText());
            u.setMoblilenum(Dismobile.getText());
            if (male_radio.isSelected()) {
                u.setGender("male");
            } else {
                u.setGender("female");
            }
            u.setBirthday(jComboBox3.getSelectedItem().toString()+"/"+jComboBox2.getSelectedItem().toString()+"/"+jComboBox1.getSelectedItem().toString());
            u.setUsername(Disusername.getText());
            u.setPassword(Dispassword.getText());
            Homepage.US.add(u);
            userTableLoad();
            Homepage.checkUsers();

        }


    }//GEN-LAST:event_jButton1ActionPerformed
private void userTableLoad(){
    DefaultTableModel dtm =(DefaultTableModel)
            signup_table.getModel();
    dtm.setRowCount(0);
    for(int i=0;i<Homepage.US.size();i++){
        Encapsulastion_class u = Homepage.US.get(i);
        Vector v = new Vector();
        v.add(u.getId());
        v.add(u.getName());
        v.add(u.getMoblilenum());
        v.add(u.getGender());
        dtm.addRow(v);
        try{
            FileOutputStream file = new FileOutputStream("E://Student_details.txt");
            ObjectOutputStream oo = new ObjectOutputStream(file);
            oo.writeObject(Homepage.US);
        }catch(IOException ex){
            System.out.println(ex);
        }
    }
            
}
        
    private void DisidKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_DisidKeyPressed
        if (evt.getKeyCode() == 10) {
            if (Disid.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "please enter valid id num", "Message box", JOptionPane.ERROR_MESSAGE);
            } else {
                Disname.grabFocus();
            }
        }
    }//GEN-LAST:event_DisidKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registrtion_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registrtion_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registrtion_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registrtion_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registrtion_form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Disaddress;
    private javax.swing.JTextField Disid;
    private javax.swing.JTextField Dismobile;
    private javax.swing.JTextField Disname;
    private javax.swing.JPasswordField Dispassword;
    private javax.swing.JTextField Disusername;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton female_radio;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton male_radio;
    private javax.swing.JTable signup_table;
    // End of variables declaration//GEN-END:variables
}
